export const siteConfig = {
    name: 'Abdulahad Hussain',
    givenName: 'Abdulahad',
    familyName: 'Hussain',
    alternateName: ['Abdul Ahad Hussain', 'Abdulahad'],
    title: 'Abdulahad Hussain | Full Stack Software Engineer',
    role: 'Full Stack Software Engineer',
    url: 'https://www.abdulahadhussain.tech',
    siteName: 'Abdulahad Hussain',
    description:
        'Official portfolio of Abdulahad Hussain, a Full Stack Software Engineer in Lahore, Pakistan building scalable web applications with React, Next.js, Vue, Node.js, and TypeScript.',
    shortDescription:
        'Full Stack Software Engineer specializing in scalable web applications, React, Next.js, Vue, Node.js, and modern cloud backend architectures.',
    email: 'abdulahadhussain60@gmail.com',
    emailUrl: 'mailto:abdulahadhussain60@gmail.com',
    profileImage: 'https://www.abdulahadhussain.tech/abdulahad-hussain.png',
    ogImage: 'https://www.abdulahadhussain.tech/opengraph-image',
    location: {
        locality: 'Lahore',
        region: 'Punjab',
        country: 'PK',
        countryName: 'Pakistan',
    },
    company: {
        name: 'BitLogicx',
    },
    alumniOf: {
        name: 'University of Engineering and Technology, Lahore',
        sameAs:
            'https://en.wikipedia.org/wiki/University_of_Engineering_and_Technology,_Lahore',
    },
    socialLinks: [
        'https://github.com/ABDULAHAD118',
        'https://www.linkedin.com/in/abdulahad018/',
        'https://www.instagram.com/abdulahadhussain8/',
    ],
    knowsAbout: [
        'Full Stack Software Engineering',
        'Web Development',
        'React',
        'Next.js',
        'Vue.js',
        'Nuxt',
        'Node.js',
        'AdonisJS',
        'TypeScript',
        'JavaScript',
        'MongoDB',
        'MySQL',
        'Redis',
        'Docker',
        'REST APIs',
        'Software Architecture',
    ],
    keywords: [
        'Abdulahad Hussain',
        'Abdulahad Hussain Software Engineer',
        'Abdulahad Hussain Developer',
        'Full Stack Software Engineer',
        'Full Stack Developer Lahore',
        'Next.js Developer Pakistan',
        'React Developer',
        'Node.js Developer',
        'Vue.js Developer',
        'AdonisJS Developer',
        'Backend Developer',
        'Frontend Developer',
        'TypeScript Developer',
        'Software Engineer Lahore',
    ],
};
